Add `<x_axis_position_angle>` attribute
pds-data-dictionaries/ldd-sb pull request #13
Opened 2024-02-09 18:14 UTC by cgobat

## Summary
Adds an `x_axis_position_angle` attribute to go with the existing `y_axis_position_angle` and `z_axis_position_angle`. See linked issue for details/rationale.

## Test Data and/or Report
LDD builds and validates and CI tests pass.

## Related Issues
- Resolves pds-data-dictionaries/PDS4-LDD-Issue-Repo#274

2024-03-06 18:12 UTC, acraugh requested changes
There's a problem. This is not a compatible change with current use, and the use of the xs:choice construct does not limit the contents of the element in a way that is sensible. It allows, for example, 3 instances of x_axis_position and none of anything else. the xs:choice construct should only ever be used when there is no other alternative, and it typically needs to be supported by one or more Schematron rules to get the desired effect. I don't see any regressions tests that would demonstrate that a) the change will not effect the existing use with MVIC data, or b) validate the appropriate constraints in labels.

2024-03-06 19:11 UTC, cgobat commented
Got it&mdash;thanks for taking a look at this. My reasoning behind this PR is that, since the present state of the dictionary&mdash;in which `x_axis_position` doesn't exist at all&mdash;entirely lacks a required functionality, and I haven't seen any discussion/movement on pds-data-dictionaries/PDS4-LDD-Issue-Repo#274 towards a resolution, I figured I would at least take a first step and propose a fix. You should be able to edit the branch associated with this PR, and you are more than welcome to add or modify anything you find missing or undesirable.

I'm not sure I agree with your assessment that
> This is not a compatible change with current use

I would think that the fact that all of the existing (and unmodified) unit test labels pass validation using the updated LDD is evidence of these changes' backwards compatibility, no?

You make a good point about how 3 instances of a single axis is currently possible. I can take a stab at writing some schematron rule(s) to make sure these attributes are used appropriately.

2024-03-06 20:22 UTC, acraugh commented
Yeah, well, that's because I'm an interrupt-driven system and most of the
messages I get from GitHub do not concern me personally, so they all get
ignored. Sort of a lack-of-guilt-by-association situation. Sorry about that.

Some background thinking:

Basically, once the dictionary is published any non-backwards compatible
change is a problem. The dictionary is critical for validation, so it is
always going to be necessary when changing an existing class to demonstrate
three things in regression tests:

   1. Currently validation is not impacted (so the current tests continue
   to produce the same results);
   2. New validation detects the correct situation (a new test);
   3. New validation detects and reports both expected and unexpected
   errors (at least one and possibly a couple of tests).

You could think of detecting unexpected errors (like three occurrences of
x_axis_position) as checking for stupid things, but it is incredibly easy
to do stupid things in a pipeline that does not include validation. I have
many examples of cases of stupid errors that reviewers never caught -
probably because they were looking for the smart errors. We have to rely on
Validate to catch the stupid ones, which means we have to make sure the
schemas are hardened against stupidity - especially in a discipline
dictionary that is used by multiple data providers.

The xs:choice option short circuits a LOT XSD of validation, so it should
be avoided unless it is absolutely essential. And honestly, it's never
essential.

So, given that the current dictionary requires y and z positions to be
present, I would need some additional information to proceed:

   - The class was defined based on the assumption that the x axis would
   always be perpendicular to the plane of the image, to correspond with the
   convention that x is associated with the instrument boresight. Under what
   circumstances is it not? ("Whim" might be a valid answer here.)
   - Will x, y, and z axis positions ever be required at the same time?
   - Is any combination of two of (x, y, z) potentially valid?
   - Is it ever valid to have a single axis position provided?
   - Is it necessary to specify whether the positive perpendicular axis
   extends out of the plane of the image, or into it?

Once I know the range of valid possibilities, and assuming they include an
x_axis_position, I can modify the class to cover the possibilities and
write Schematron rules to enforce the appropriate existential requirements
among the positions if needed. Then I need to update the internal and
external documentation, write and run the regressions tests, build the
schemas and test again locally before declaring victory.

If you happen to know the answers to the above questions, I could at least
get the schemas built for development in relatively short order (like, a
day). Otherwise I'll need to quiz the SBN observers for their collective
experience, and investigate what's going on in whatever instrument in NH is
prompting the change. That will take more like a week.

-Anne.


On Wed, Mar 6, 2024 at 2:12 PM Caden Gobat ***@***.***> wrote:

> Got it—thanks for taking a look at this. My reasoning behind this PR is
> that, since the present state of the dictionary—in which x_axis_position
> doesn't exist at all—entirely lacks a required functionality, and I haven't
> seen any discussion/movement on
> pds-data-dictionaries/PDS4-LDD-Issue-Repo#274
> <https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/issues/274>
> towards a resolution, I figured I would at least take a first step and
> propose a fix. You should be able to edit the branch associated with this
> PR, and you are more than welcome to add or modify anything you find
> missing or undesirable.
>
> I'm not sure I agree with your assessment that
>
> This is not a compatible change with current use
>
> I would think that the fact that all of the existing (and unmodified) unit
> test labels pass validation using the updated LDD is evidence of these
> changes' backwards compatibility, no?
>
> You make a good point about how 3 instances of a single axis is currently
> possible. I can take a stab at writing some schematron rule(s) to make sure
> these attributes are used appropriately.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pds-data-dictionaries/ldd-sb/pull/13#issuecomment-1981597110>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADBV2QFK4754NAADJJNJKEDYW5S7ZAVCNFSM6AAAAABDB4BDRCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSOBRGU4TOMJRGA>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-03-06 21:45 UTC, cgobat commented
> The class was defined based on the assumption that the x axis would always be perpendicular to the plane of the image, to correspond with the convention that x is associated with the instrument boresight. Under what circumstances is it not? ("Whim" might be a valid answer here.)

For New Horizons alone:

| Instrument | Boresight axis |
| --- | --- |
| Alice | +Y |
| LEISA | -X |
| LORRI | -Z |
| MVIC | -X |
| PEPSSI | +Z |
| REX | +Z |
| SDC | +Z |
| SWAP | +Y |

For brevity, I'll refrain from providing a similar table for Lucy's instruments, which would contain a comparable mix of boresight definitions. I can only assume that NH and Lucy are not outliers in this sense, and that many or most other missions probably have instrument(s) whose boresights are not aligned with their x-axis.

So, even in practice (let alone in theory), it's not safe to assume that x is the boresight axis for all (or even most) instruments.

---

> Will x, y, and z axis positions ever be required at the same time?

Maybe not in practice, but one could in theory conceive of an instrument whose boresight does not align with any of it's x, y, or z axes. In this case I think all three position angles would be required in order to fully specify the orientation.

---

> Is any combination of two of (x, y, z) potentially valid?

Yes.

---

> Is it ever valid to have a single axis position provided?

Not in any realistic scenario I can think of.

---

> Is it necessary to specify whether the positive perpendicular axis extends out of the plane of the image, or into it?

I think in theory that information is already encoded in the orientation of the other two axes relative to each other in the image plane (e.g., if Z is 90&deg; clockwise of Y, X points into the page, whereas if Y is 90&deg; clockwise from Z, X points out of the page).

---

Regarding the philosophical concerns with using an xs:choice&ndash; what would be a better option here? I know it is always possible to specify all of your desired behavior through a set of schematron rules, but that doesn't seem great either, design intent wise...

2024-03-06 22:24 UTC, acraugh commented
So "whim" *was *the answer. Not all that surprising, really.

Well, if it's true that the right-hand rule always applies (is it?), then
it is sufficient to require that exactly two axis positions are always
specified. That is true in the original use case, so that's a compatible
change. What we need, then, is: a new x_axis_position attribute to add to
the Instrument_Position_Angles class; the cardinality of each axis_position
to be 0:1; a Schematron rule to ensure that exactly two axis_position
values are always present (count the child nodes and make sure the count is
exactly '2');  a regression test to demonstrate that a pair with
x_axis_position is considered valid; and a regression test to demonstrate
that including zero, one, or three axis_positions is invalid. (The
complication of an instrument that somehow records image data askew to its
boresight can be dealt with if and when it arises.) All the definitions
need to be updated to indicate that a right-hand rule is assumed to apply,
and I should fix a typo or two while we're at it. Then we need to check if
an update to the manually maintained user documentation is needed (it might
not be for this) and we're ready to roll. Fairly simple.

You could not actually get that validation with an xs:choice without
writing a substantially more complicated (and more expensive to execute)
Schematron rule, possibly two, because of the weird effects that you get
with min/max occurrence settings for the list and for individual elements.
Or at least that was the case last time I tested, which was a couple minor
versions of the Saxon library ago...

-Anne.


On Wed, Mar 6, 2024 at 4:45 PM Caden Gobat ***@***.***> wrote:

> The class was defined based on the assumption that the x axis would always
> be perpendicular to the plane of the image, to correspond with the
> convention that x is associated with the instrument boresight. Under what
> circumstances is it not? ("Whim" might be a valid answer here.)
>
> For New Horizons alone:
> Instrument Boresight axis
> Alice +Y
> LEISA -X
> LORRI -Z
> MVIC -X
> PEPSSI +Z
> REX +Z
> SDC +Z
> SWAP +Y
>
> For brevity, I'll refrain from providing a similar table for Lucy's
> instruments, which would contain a comparable mix of boresight definitions.
> I can only assume that NH and Lucy are not outliers in this sense, and that
> many or most other missions probably have instrument(s) whose boresights
> are not aligned with their x-axis.
>
> So, even in practice (let alone in theory), it's not safe to assume that x
> is the boresight axis for all (or even most) instruments.
> ------------------------------
>
> Will x, y, and z axis positions ever be required at the same time?
>
> Maybe not in practice, but one could in theory conceive of an instrument
> whose boresight does not align with any of it's x, y, or z axes. In this
> case I think all three position angles would be required in order to fully
> specify the orientation.
> ------------------------------
>
> Is any combination of two of (x, y, z) potentially valid?
>
> Yes.
> ------------------------------
>
> Is it ever valid to have a single axis position provided?
>
> Not in any realistic scenario I can think of.
> ------------------------------
>
> Is it necessary to specify whether the positive perpendicular axis extends
> out of the plane of the image, or into it?
>
> I think in theory that information is already encoded in the orientation
> of the other two axes relative to each other in the image plane (e.g., if Z
> is 90° clockwise of Y, X points into the page, whereas if Y is 90°
> clockwise from Z, X points out of the page).
> ------------------------------
>
> Regarding the philosophical concerns with using an xs:choice– what would
> be a better option here? I know it is always possible to specify all of
> your desired behavior through a set of schematron rules, but that doesn't
> seem great either, design intent wise...
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pds-data-dictionaries/ldd-sb/pull/13#issuecomment-1981854609>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADBV2QE6NEFND4ZUSRWQAP3YW6FBDAVCNFSM6AAAAABDB4BDRCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSOBRHA2TINRQHE>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-03-07 19:11 UTC, acraugh commented on build/development/135fa36016cd13cadd6b395397509df16e2118d5/1.19.0.0/PDS4_SB_1J00_1000.txt
There has been no update to the descriptions to indicate that there is an assumption of a right-hand rule for the axes. This needs to be added to the class description at least; possibly the three axis_position_angle definitions.

2024-03-07 19:28 UTC, acraugh commented on logs/v1.19.0.0_execution_logs/validate_report_20240307190009.txt
This regression test appears to fail primarily for the wrong reason. It is failing because nothing is allowed to follow sb:z_axis_position in the class, not because sb:z_axis_position has been duplicated. The Schematron rule does fire, but schema errors tend to override Schematron errors in practice (an invalid schema tends to cause spurious Schematron errors). There should also be either a separate test or an alteration to an existing VALID test (referenced in a comment here) that demonstrates that the Schematron rule does NOT fire for valid input that includes sb:x_axis_position.

2024-03-07 19:31 UTC, acraugh commented on src/PDS4_SB_IngestLDD.xml
I'm not seeing anything in the axis_position_angle attribute definitions or a change to the Instriment_Position_Angles class to indicate that there is an assumption of a right-hand rule in describing the orientation of these axes.

2024-03-07 19:33 UTC, acraugh requested changes
Need a couple of clean-up details in the attribute/class descriptions and in the regression test added. I'll check the user documentation to see if an update is needed for this specifically.

2024-03-07 19:37 UTC, acraugh commented
I checked the user docs. There is a minor update needed in the namespace outline page. I'll do this myself when we're ready, since I need to think how to present the information concisely, for situations like this class, and because of the annoying complications with building documents in branches to begin with.

2024-03-07 20:20 UTC, cgobat commented on src/PDS4_SB_IngestLDD.xml
Here is a draft of some text to be added to the `<definition>` of the `Instrument_Position_Angles` class:

> Only two axes should be specified, with the third being the instrument's
  boresight. Note that the instrument frame's axis orientation is assumed to
  be right-handed, so the direction of the boresight axis (into or out of the
  image plane) can be inferred from the relative positions of the other two.

How does that sound?

2024-03-07 21:06 UTC, acraugh commented
Sounds good to me!

Thanks,

-Anne.


On Thu, Mar 7, 2024 at 3:21 PM Caden Gobat ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> On src/PDS4_SB_IngestLDD.xml
> <https://github.com/pds-data-dictionaries/ldd-sb/pull/13#discussion_r1516770615>
> :
>
> Here is a draft of some text to be added to the <definition> of the
> Instrument_Position_Angles class:
>
> Only two axes should be specified, with the third being the instrument's
> boresight. Note that the instrument frame's axis orientation is assumed to
> be right-handed, so the direction of the boresight axis (into or out of the
> image plane) can be inferred from the relative positions of the other two.
>
> How does that sound?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pds-data-dictionaries/ldd-sb/pull/13#discussion_r1516770615>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADBV2QFM4JWINSOKNBQ6YX3YXDD25AVCNFSM6AAAAABDB4BDRCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSMRTGQ2TGNBQGA>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-03-07 21:14 UTC, cgobat commented on logs/v1.19.0.0_execution_logs/validate_report_20240307190009.txt
4f2b486 should fix

2024-03-12 21:10 UTC, cgobat commented
Is there anything else this is waiting on?

2024-05-03 17:34 UTC, cgobat commented
Can we merge this? @acraugh

2024-05-03 18:34 UTC, acraugh commented
For some reason I thought I had already. Yes, I believe so. I'll
double-check and do that now...

-Anne.


On Fri, May 3, 2024 at 1:34 PM Caden Gobat ***@***.***> wrote:

> Can we merge this? @acraugh <https://github.com/acraugh>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pds-data-dictionaries/ldd-sb/pull/13#issuecomment-2093473511>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADBV2QA3V7W5G76NNNDC7JLZAPDDXAVCNFSM6AAAAABDB4BDRCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAOJTGQ3TGNJRGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-05-03 18:50 UTC, acraugh approved these changes

2024-05-03 18:51 UTC, acraugh commented
Had to add some missing documentation updates in the user docs and the test/ directory Readme, but otherwise OK.

2024-05-03 18:52 UTC, merged